name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4


    # SAST
    - name: Run Semgrep SAST
      uses: semgrep/semgrep-action@v1
      with:
        config: |
          p/python
          p/owasp-top-ten


    # Secret scanning
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2


    # Dependency and filesystem scan
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        severity: CRITICAL,HIGH


    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t devsecops-demo:${{ github.sha }} .
